{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red49\green49\blue49;\red234\green234\blue234;\red83\green83\blue83;
\red29\green111\blue63;\red150\green204\blue255;\red12\green14\blue18;}
{\*\expandedcolortbl;;\cssrgb\c25098\c25098\c25098;\cssrgb\c93333\c93333\c93333;\cssrgb\c40000\c40000\c40000;
\cssrgb\c12549\c50196\c31373;\cssrgb\c64706\c83922\c100000;\cssrgb\c5098\c6667\c9020;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
name: periopmortality\
channels:\
  \cf4 -\cf2  anaconda\
\
dependencies:\
  \cf4 -\cf2  python\cf4 =\cf5 3.6\cf2 \
  \cf4 -\cf2  numpy\cf4 =\cf5 1.19\cf4 .*\
\pard\pardeftab720\partightenfactor0
\cf4 \cb3   - 
\f1 \cf6 \cb7 scikit-learn=0.21.3\

\f0 \cf4 \cb3   - pandas=1.4.*\
  - 
\f1 \cf6 \cb7 scipy=1.5.*
\f0 \cf4 \cb3 \
  - \cf2 \cb3 gensim=4.1.2\cf4 \cb3 \
  - 
\f1 \cf6 \cb7 xgboost
\f0 \cf4 \cb3 \
  - Boruta\
  -\cf2 \cb3  nltk \
\pard\pardeftab720\partightenfactor0
\cf2 \cb3   \cf4 \cb3 -\cf2 \cb3  tqdm\
  \cf4 \cb3 -\cf2 \cb3  pickle\cf4 \cb3 \
  - 
\f1 \cf6 \cb7 matplotlib\
\pard\pardeftab720\partightenfactor0

\f0 \cf4 \cb3   - json\
}