name: periopmortality
channels:
  - anaconda
  
dependencies:
  - python=3.6
  - numpy=1.19.*
  - scikit-learn=0.21.3
  - pandas=1.4.*
  - scipy=1.5.*
  - gensim=4.1.2
  - nltk
  - matplotlib
  - xgboost
  - Boruta
  - json
  - seaborn
  - tqdm